-- CRIANDO TABELAS E REGRAS
-- COMANDSOS : 3 DE DDL, 3 DE CONTROLE, 3 DE MANIPULAÇÃO

DROP TABLE TA1; -- COM CASCADE CONSTRAINT ELIMINA AS REGRAS QUE ESTÃO EM OUTRAS TABELAS JUNTOS A TABELA 
CREATE TABLE TA1 /* CRIA TABELA TA1 */
(
C1     NUMBER,     /* DEVE CRIAR PELO MENOS UMA COLUNA */
C2     CHAR,
C3     VARCHAR2(100)
--CONSTRAINT  PK_TA1 PRIMARY KEY (C1, C2),
--CONSTRAINT  CK_TA1_C1 CHECK (C1 > 0)
);
-- TIPOS DE VALOR NUMBER(5,2) NO MAX 3(5-2) INTEIROS E 2 CASAS DECIMAIS, 
--VARCHAR(100) SEMPRE 0CUPA ESPAÇO DE 100, VANTAJOSO APENAS QUANDO SE SABE QUE VAI UTILIZAR O TAMANHO TOTAL DO VARCHAR, 
-- JÁ VARCHAR2 ECONOMIZA POR USAR APENAS O QUE É USADO, USA MAIS PROCESSAMENTO E MENOS E MEMÓRIA E O VARCHAR É O CONTRÁRIO.
-- CHAR 
-- DATE 

-- ALTERANDO A ESTRUTURA DE TABELA
ALTER TABLE TA1
ADD CONSTRAINT PK_TA1 PRIMARY KEY (C1)
ADD CONSTRAINT  CK_TA1_C1 CHECK (C1 > 0)
MODIFY C2 NOT NULL
MODIFY C3  VARCHAR2(80);

ALTER TABLE TA1
DROP COLUMN C2;

-- VERIFICANDO A TABELA CRIADA NO DD (DICIONÁRIO DE DADOS / CATÁLOGO)
DESC TA1; -- DESCREVE A ESTRUTURA DA TABELA/VIEW

-- BUSCANDO INFROMAÇÕES SOBRE TABELAS NO CATÁLOGO
SELECT OBJECT_NAME
FROM ALL_OBJECTS
WHERE OBJECT_TYPE = 'VIEW'
    AND OBJECT_NAME LIKE '%TABLE%';

-- MOSTRA A TABELA DE USUARIOS
SELECT *
FROM USER_TABLES
WHERE TABLE_NAME= 'TA1'; -- TA1 TEM QUE SER MAISCULO POIS CONTEÚDO É SEMPRE MAIÚSCULO

-- VERIFICANDO AS COLUNAS DA TABELA/VIEW
SELECT *
FROM USER_TAB_COLUMNS  
WHERE TABLE_NAME='TA1';

-- VERIFICANDO AS REGRAS (CONSTRAINTS) TABELA/VIEW
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='TA1';

-- VERIFICANDO AS REGRAS (CONSTRAINTS) APLICADAS EM QUAL COLUNA DA TABELA/VIEW
SELECT *
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='TA1';

-- VERIFICANDO ÍNDICES DA TABELA/VIEW
SELECT *
FROM USER_INDEXES
WHERE TABLE_NAME='TA1';

-- VERIFICANDO AS COLUNAS DE ÍNDICES DA TABELA/VIEW
SELECT *
FROM USER_IND_COLUMNS
WHERE TABLE_NAME='TA1';

-- CRIANDO TA2
DROP TABLE TA2;
CREATE TABLE TA2(
COL     NUMBER(2) CONSTRAINT PK_TA2 PRIMARY KEY,
COL_C1  NUMBER
);

-- INCLUINDO A CONSTRANT (REGRA) DE FK EM TA2 REFERENCIANDO TA1
ALTER TABLE TA2
ADD CONSTRAINT FK_TA2_TA1 FOREIGN KEY (COL_C1) REFERENCES TA1 (C1);

-- IINCLUINDO DADOS EM TA2
INSERT INTO TA2 VALUES (1,NULL);
INSERT INTO TA2 VALUES (2,1);

-- MOSTRA A TABELA DE USUARIOS
SELECT *
FROM USER_TABLES
WHERE TABLE_NAME IN ('TA1', 'TA2'); -- TA1 TEM QUE SER MAISCULO POIS CONTEÚDO É SEMPRE MAIÚSCULO

-- VERIFICANDO AS COLUNAS DA TABELA/VIEW
SELECT *
FROM USER_TAB_COLUMNS  
WHERE TABLE_NAME IN ('TA1', 'TA2');

-- VERIFICANDO AS REGRAS (CONSTRAINTS) TABELA/VIEW
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('TA1', 'TA2');

-- VERIFICANDO AS REGRAS (CONSTRAINTS) APLICADAS EM QUAL COLUNA DA TABELA/VIEW
SELECT *
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME IN ('TA1', 'TA2');

-- VERIFICANDO ÍNDICES DA TABELA/VIEW
SELECT *
FROM USER_INDEXES
WHERE TABLE_NAME IN ('TA1', 'TA2');

-- VERIFICANDO AS COLUNAS DE ÍNDICES DA TABELA/VIEW
SELECT *
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN ('TA1', 'TA2');
