-- O DUPLO SINAL DE MENOS COMENTA TODA A LINHA A PARTIR DO MESMO

/*
Tudo entre esses /* vira comentario
*/
SELECT * -- * INDICA QUE VAI TRAZER TODAS AS COLUNAS DA TABELA
FROM EMP; -- TODA QUERY ACABA COM PONTO-VIRGULA

SELECT FIRST_NAME
FROM EMP;

/*
SELECT -- PROJETA AS COLUNAS DESEJADAS NA ORIGEM FROM
FROM -- RELACIONA A ORIGEM ONDE ESTAO OS DADOS A SEREM CONSULTADOS
WHERE -- FAZ A RESTRICAO (FILTRO) DAS LINHAS A SEREM MOSTRADAS CONFORME UMA CONDICAO
      -- OPERADORES PARA DEFINIR UMA CODNICAO: =, <> (!=), >=, <=, <, >, NOT, AND, OR
                                                BETWEEN, LIKE , IN
GROUP BY -- DEFINIR OU ESTABELECER SUBGRUPOS NO RESULTADO DA QUERY
HAVING -- FILTRAR OS SUBGRUPOS FORMADOS CONFORME UMA CONDICAO
ORDER BY -- ORDENAR O RESULTADO APRESENTADO,CRESCENTE OU DESCRESCENTE POR COLUNAS
*/

-- PRODUZINDO RESULTADO CONSTANTES
SELECT 1234323 / 312451 CALC1, 
    TO_CHAR(SYSDATE, 'DD-MM-YYYY') "DATA DE HOJE", -- TO_CHAR: FORMATA PARA STRING, NESSE CASO ELE INTERPRETA COMO UMA DATA E FAZ NA ORDEM Q VOCE QUYE
    'Teste' AS STRING,
    5 AS NUMERO
FROM DUAL; -- CRIA AUTOMATICAMENTE UMA NOVA TABELA

SELECT ROUND(5/6) AS CALC1,
    "TESTE" AS STRING,
    5 AS NUMERO,
    FIRS_NAME AS PRIMEIRO_NOME -- MUDA O NOME DA TABELA
FROM EMP;

-- VERIFICANDO E ANALISANDO METADADOS DO DICIONARIO DE DADOS DINAMICO(CATALOGO)
DESC ALL_OBJECTS; -- DESC DESCREVE UMA ESTRUTA DE UMA TABELA OU VIEW

SELECT *
FROM ALL_OBJECTS;

SELECT COUNT(*) -- CONTA QAUNTOS OBEJTOS TEM
FROM ALL_OBJECTS;

SHOW USER;

SELECT DISTINCT OBEJECT_TYPE
FROM ALL_OBJECTS;

-- VERIFICAR OS OBJETOS EXISTENTES A PARTIR DE UM FILTRO COM PALAVRAS DE INTERESSE
SELECT OBJECT_NAME
FROM ALL_OBJECTS
WHERE OBJECT_TYPE='VIEW';

-- BUSCANDO INFORMACOES SOBRE TABELAS NO CATALOGO (DD)
SELECT OBJECT_NAME
FROM ALL_OBJECTS
WHERE OBJECT_TYPE='VIEW'
    AND (OBJECT_NAME LIKE '_____TAB%COL%' -- Conotacao: 5Underline considera que eh aquela quantiade(5) de carcteres mas sem especicar qual, depois TAB, 
                                            -- %Qualquer quantidade de caracteres, COL, %Qualquer quantiade dnv
    OR OBJECT_NAME LIKE 'U%TAB%COL%');
